name: cs7643-final-project
channels:
  - defaults
dependencies:
  - python==3.8.10
  - matplotlib
  - tqdm
  - jupyter
  - pip
  - pip:
    - torch
    - notebook
    - numpy
    - torchvision
    - pandas
    - pyarrow
    - fastparquet

